### ISSUE TITLE
Dub, Window x64, LDC, Derelict : unable to compile

### ISSUE THREAD

**Issue by SrMordred** [ldc-developers/ldc#1766]
LLVM D compiler (1a7070): based on DMD v2.071.2-b2 and LLVM 3.9.0git-fbbabf3

command: dub run --build=release --arch=x86_64 --compiler=D:/ldc/bin/ldc2.exe

Output:

Performing "release" build using D:/ldc/bin/ldc2.exe for x86_64.
derelict-util 2.0.6: building configuration "library"...
Error: failed to create path to file: .dub\obj\..\..\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util\.dub\build\library-release-windows-x86_64-ldc_0-E1A9179AF0D6E609F102DF89BE3F74F1\DerelictUtil.lib
no such file or directory
D:/ldc/bin/ldc2.exe failed with exit code 1.

changing to DMD compiler works properly.

**Comment by JohanEngelen** [comment]
Can you give a full recipe to reproduce it? (i.e. start from `dub init`)
(not many of us here use dub very often, i think)

**Comment by SrMordred** [comment]
`dub init example --format=sdl`
`cd example`
Edit dub.sdl file  , add this line:
`dependency "derelict-sdl2" version="~>2.0.1"`
`dub run --build=release --arch=x86_64 --compiler=D:/ldc/bin/ldc2.exe`
Done :)

**Comment by rainers** [comment]
> Error: failed to create path to file: .dub\obj....\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util.dub\build\library-release-windows-x86_64-ldc_0-E1A9179AF0D6E609F102DF89BE3F74F1\DerelictUtil.lib
> no such file or directory

I could not reproduce the problem here, but the file path looks suspicious: it looks as if you are building in your home directory? Maybe dub has an issue with different drives for project, dub registry and compiler?

Please add --verbose to the dub command line and show the failing command line.

**Comment by SrMordred** [comment]
Ok,  thought that it maybe be something related to large paths so i tried on c:/ and it works. 
Then i tried again on the original case and it worked too, have no idea what happened.

**Comment by kinke** [comment]
I'll close this then.

**Comment by jairov4** [comment]
It is still happening to me with LDC-1.1.0-beta3
Im using the source code in C:\
and the compiler from D:\

**Comment by kinke** [comment]
Please check latest [Windows CI build](https://github.com/ldc-developers/ldc/releases/tag/LDC-Win64-master), this should definitely be fixed now (see https://github.com/ldc-developers/ldc/issues/1819).
