### ISSUE TITLE
Global variable initializer type does not match global variable type

### ISSUE THREAD

**Issue by MrSmith33** [ldc-developers/ldc#2108]
```
Global variable initializer type does not match global variable type!
%voxelman.graphics.font.textmesher.TextMesherParams* @_D8voxelman8graphics4font10textmesher16TextMesherParams6__initZ
LLVM ERROR: Broken module found, compilation aborted!
ldc2 failed with exit code 1.
```

Fails on 1.2.0 and 1.3.0-beta1 on Windows
Upd: And 1.1.1

P.S. Can we have debug release?

**Comment by ennis** [comment]
The following code seems to trigger the same error:

	import std.stdio;

	struct Vec
	{
	    float v; 
	}

	struct Quat
	{
		union
		{
			Vec v;   // replacing this line with 'float v;' makes the error disappear
			struct
			{
				float x;
			}
		}

		@nogc static Quat identity() pure nothrow @property
		{
			Quat q;
			q.x = 1;  // commenting this line makes the error disappear
			return q;
		}
	}

	struct S 
	{
		Quat q = Quat.identity;
	}

	static Quat q = Quat.identity;

	void main()
	{
	}

Compiler output:

	Global variable initializer type does not match global variable type!
	%app.S* @_D3app1S6__initZ
	LLVM ERROR: Broken module found, compilation aborted!


Output of `ldc2 -version`:

	LDC - the LLVM D compiler (1.3.0-beta1):
	based on DMD v2.073.2 and LLVM 3.9.1
	built with LDC - the LLVM D compiler (1.3.0-beta1)
	Default target: x86_64-pc-windows-msvc
	Host CPU: haswell

**Comment by ennis** [comment]
Reduced with dustmite:

	struct Vec
	{
	}

	struct Quat
	{
		union
		{
			Vec v;
			struct
			{
				float x;
			}
		}

		static identity() 
		{
			Quat q;
			q.x = 1;
			return q;
		}
	}

	struct S 
	{
		Quat q = Quat.identity;
	}

Also fails on 1.3.0-beta2

**Comment by kinke** [comment]
Thank you very much @ennis.

**Comment by kinke** [comment]
```D
struct Vec { float v; }

struct Quat
{
	union
	{
		Vec v;
		struct { float x; }
	}

	@nogc static Quat identity() pure nothrow @property
	{
		Quat q;
		q.x = 1; // q.v.v = 1;
		return q;
	}
}

struct S 
{
	Quat q = Quat.identity;
}
````

Crashes with initializer type mismatch. The commented-out code also crashes, but this time when generating the ModuleInfo... a jewel of a testcase.

**Comment by kinke** [comment]
The potentially multiple LL types for a single union, depending on how they are initialized, are also the reason for nasty issue https://github.com/ldc-developers/ldc/issues/1829.

**Comment by kinke** [comment]
ennis' testcase fixed by #2171.

@MrSmith33: Please check again with Windows CI build **3897** [here](https://github.com/ldc-developers/ldc/releases/tag/LDC-Win64-master). It should be downloadable in about half an hour.

**Comment by MrSmith33** [comment]
@kinke:
On first try I got `LLVM ERROR: Could not acquire a cryptographic context: Unknown error (0x7F)`
On second I and consecutive I get `Error: out of memory`
LDC uses only 1.8 Gigs of memory

**Comment by kinke** [comment]
Are you using the 64-bit build?

**Comment by MrSmith33** [comment]
I downloaded `LDC-master-3911-multilib.7z` on Windows 10

**Comment by MrSmith33** [comment]
I tried splitting project into two parts. One part still fails with `.dub\obj\client.obj: not enough memory`

**Comment by MrSmith33** [comment]
It seems to compile now, but fails to link with some system libs, (possibly a dub bug)

I have `"libs-windows": ["user32", "gdi32", "ws2_32", "winmm"],` in `dub.json`
```
ws2_32.lib(WS2_32.dll) : error LNK2005: htons already defined in druntime-ldc.lib(winsock2.obj)
ws2_32.lib(WS2_32.dll) : error LNK2005: ntohs already defined in druntime-ldc.lib(winsock2.obj)
ws2_32.lib(WS2_32.dll) : error LNK2005: ntohl already defined in druntime-ldc.lib(winsock2.obj)
ws2_32.lib(WS2_32.dll) : error LNK2005: htonl already defined in druntime-ldc.lib(winsock2.obj)
   Creating library .dub\build\application-debug-windows-x86_64-ldc_2073-0BF793B79011CBF99FDC78FD7F053D86\editor.lib and object .dub\build\application-debug-windows-x86_64-ldc_2073-0BF793B79011CBF99FDC78FD7F053D86\editor.exp
cimgui.lib(imgui.obj) : error LNK2019: unresolved external symbol _vacopy referenced in function "public: void __cdecl ImGuiTextBuffer::appendv(char const *,char *)" (?appendv@ImGuiTextBuffer@@QEAAXPEBDPEAD@Z)
enet.lib(win32.o) : error LNK2019: unresolved external symbol __imp_timeBeginPeriod referenced in function enet_initialize
enet.lib(win32.o) : error LNK2019: unresolved external symbol __imp_timeEndPeriod referenced in function enet_deinitialize
enet.lib(win32.o) : error LNK2019: unresolved external symbol __imp_timeGetTime referenced in function enet_host_random_seed
.dub\build\application-debug-windows-x86_64-ldc_2073-0BF793B79011CBF99FDC78FD7F053D86\editor.exe : fatal error LNK1120: 4 unresolved externals
Error: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe failed with status: 1120
ldc2 failed with exit code 1120.
```

**Comment by kinke** [comment]
Alright, the original issue seems to be fixed as expected then, thanks for confirming -> closing.
